import Header from "@/components/header";
import MobileHeader from "@/components/mobile-header";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Chakra_Petch as FontSans } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-black text-white font-sans antialiased",
          fontSans.variable
        )}
      >
        <Header />
        <MobileHeader />
        {children}
      </body>
    </html>
  );
}
